#!/usr/bin/env bun
/**
 * wt — deterministic worktree/instance manager for the OpenTag box.
 *
 * One "instance" = fluso-frontend + premapp-backend worktrees for a slug,
 * running on a slot's port block, reachable at <slug>.local-pcci.org (FE),
 * <slug>-api.local-pcci.org (BE) and <slug>-agents.local-pcci.org (gateway).
 *
 * Design: infra/DESIGN.md. Humans and the Slack agent both call this; the
 * agent is prompted to NEVER hand-roll ports/env/tunnel edits.
 *
 * Runs as user `omni`. The single root-privileged step (cloudflared ingress)
 * goes through `sudo /usr/local/bin/opentag-ingress` (see ingress-helper.sh,
 * installed with a NOPASSWD sudoers entry scoped to that command).
 */
import { execFileSync, execFile } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  chmodSync,
  readdirSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";

// ── Layout ──────────────────────────────────────────────────────────────────
const HOME = homedir();
const STATE_DIR = process.env["OPENTAG_STATE_DIR"] ?? join(HOME, ".opentag");
const REGISTRY = join(STATE_DIR, "instances.json");
const TEMPLATES = join(STATE_DIR, "env-templates");
const REPOS = process.env["OPENTAG_REPOS_DIR"] ?? join(HOME, "repos");
const WORKTREES = process.env["OPENTAG_WORKTREES_DIR"] ?? join(HOME, "worktrees");
const PORTS_MD = join(WORKTREES, "PORTS.md");
const BUILD_LOCK = join(STATE_DIR, "fe-build.lock");
const DEPS_COMPOSE = join(dirname(new URL(import.meta.url).pathname), "deps-compose.yml");
const DOMAIN = process.env["OPENTAG_DEPLOY_DOMAIN"] ?? "local-pcci.org";
const BASE_BRANCH = process.env["OPENTAG_BASE_BRANCH"] ?? "dev";

const FE_REPO = "fluso-frontend";
const BE_REPO = "premapp-backend";

// Shared infra (opentag-deps compose project) — fixed, slot-independent.
const DEPS = { pg: 35432, localstack: 34566, redis: 36379 };

// ── Slots ───────────────────────────────────────────────────────────────────
// Slot N ∈ {3..9}: 1/2 are the legacy root-side deployments (mcp, permv2).
// Slots 3–5 keep the box's historic N*10000 port blocks (already deployed and
// documented in PORTS.md); that scheme overflows the port range past slot 5,
// so slots 6–9 use N*1000 blocks with the same service offsets. Ports are
// frozen into the registry per instance at create time, so changing this map
// never moves a live instance.
const SLOTS = [3, 4, 5, 6, 7, 8, 9] as const;
const portsFor = (slot: number) => {
  const block = slot <= 5 ? slot * 10000 : slot * 1000;
  return {
    fe: 3000 + slot * 10, //  3030 … 3090
    be: block + 8000, // 38000/48000/58000, then 14000/15000/16000/17000
    agents: block + 4111,
    pcci: block + 3005,
    chrono: block + 7668,
  };
};

// ── Registry ────────────────────────────────────────────────────────────────
interface Instance {
  slug: string;
  issue?: string;
  branch: string;
  slot: number;
  repos: string[]; // which of [FE_REPO, BE_REPO] the instance runs
  ports: ReturnType<typeof portsFor>;
  state: "created" | "running" | "stopped";
  /**
   * Backend the frontend talks to. "local" = this instance's own uvicorn (full
   * stack). "dev" = the DEPLOYED dev backend (api.dev.khichdi.cc) — used for
   * frontend-only changes, so no local BE/agents/db is provisioned or started.
   */
  backend?: "local" | "dev";
  withChronograph?: boolean;
  createdAt: string;
  updatedAt: string;
}
type Registry = { version: 1; instances: Record<string, Instance> };

function loadRegistry(): Registry {
  try {
    return JSON.parse(readFileSync(REGISTRY, "utf8")) as Registry;
  } catch {
    return { version: 1, instances: {} };
  }
}
function saveRegistry(reg: Registry): void {
  mkdirSync(STATE_DIR, { recursive: true });
  writeFileSync(REGISTRY, JSON.stringify(reg, null, 2));
  renderPortsMd(reg);
}
function renderPortsMd(reg: Registry): void {
  const rows = Object.values(reg.instances)
    .sort((a, b) => a.slot - b.slot)
    .map(
      (i) =>
        `| ${i.slot} | ${i.slug} | ${i.issue ?? "-"} | ${i.branch} | fe:${i.ports.fe} be:${i.ports.be} ag:${i.ports.agents} | ${i.state} |`,
    );
  mkdirSync(WORKTREES, { recursive: true });
  writeFileSync(
    PORTS_MD,
    [
      "# OpenTag instance port map (generated by `wt` — do not edit)",
      "",
      `Shared deps: postgres:${DEPS.pg} localstack:${DEPS.localstack} redis:${DEPS.redis}`,
      "Slots 1–2 are the legacy root-side deployments (mcp, permv2). See /root/wt/PORTS.md.",
      "",
      "| slot | slug | issue | branch | ports | state |",
      "|---|---|---|---|---|---|",
      ...rows,
      "",
    ].join("\n"),
  );
}

// ── Small helpers ───────────────────────────────────────────────────────────
const log = (m: string) => console.log(m);
const die = (m: string): never => {
  console.error(`wt: ${m}`);
  process.exit(1);
};
function sh(cmd: string, args: string[], opts: { cwd?: string; env?: Record<string, string> } = {}): string {
  return execFileSync(cmd, args, {
    cwd: opts.cwd,
    env: { ...process.env, ...opts.env },
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    maxBuffer: 1 << 24,
  });
}
function shOk(cmd: string, args: string[], opts: { cwd?: string } = {}): boolean {
  try {
    sh(cmd, args, opts);
    return true;
  } catch {
    return false;
  }
}
const tmuxName = (slug: string, proc: string) => `wt_${slug}_${proc}`;
const hostnames = (slug: string) => ({
  fe: `${slug}.${DOMAIN}`,
  be: `${slug}-api.${DOMAIN}`,
  agents: `${slug}-agents.${DOMAIN}`,
});
const dbName = (slug: string) => `opentag_${slug.replace(/[^a-z0-9]/g, "_")}`;

function portFree(port: number): boolean {
  // ss prints one line per listener; grep exact ":port " match.
  const out = sh("ss", ["-tln"]);
  return !new RegExp(`[:.]${port}\\s`).test(out);
}

async function waitFor(desc: string, url: string, timeoutS: number): Promise<void> {
  const until = Date.now() + timeoutS * 1000;
  let lastErr = "";
  while (Date.now() < until) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(4000) });
      if (res.ok) return;
      lastErr = `HTTP ${res.status}`;
    } catch (e) {
      lastErr = String(e);
    }
    await new Promise((r) => setTimeout(r, 3000));
  }
  die(`${desc} did not become healthy at ${url} (${lastErr})`);
}

// ── Env rendering ───────────────────────────────────────────────────────────
/**
 * Render one golden template with the instance's identity. Placeholders are
 * {{SLUG}} {{FE_PORT}} {{BE_PORT}} {{AG_PORT}} {{PCCI_PORT}} {{CG_PORT}}
 * {{DB_NAME}} {{DB_PORT}} {{DB_HOST}} {{DOMAIN}}. Secrets live in the
 * template files (mode 0600, seeded by infra/wt/seed-templates.sh) and are
 * copied through verbatim — this tool never prints env contents.
 */
function renderEnv(inst: Instance, template: string, dest: string): void {
  const src = join(TEMPLATES, template);
  if (!existsSync(src)) die(`missing template ${src} — run seed-templates.sh (see infra/DESIGN.md §3)`);
  const map: Record<string, string> = {
    SLUG: inst.slug,
    DOMAIN,
    FE_PORT: String(inst.ports.fe),
    BE_PORT: String(inst.ports.be),
    AG_PORT: String(inst.ports.agents),
    PCCI_PORT: String(inst.ports.pcci),
    CG_PORT: String(inst.ports.chrono),
    DB_NAME: dbName(inst.slug),
    DB_HOST: "127.0.0.1",
    DB_PORT: String(DEPS.pg),
    LOCALSTACK_PORT: String(DEPS.localstack),
    REDIS_PORT: String(DEPS.redis),
  };
  const body = readFileSync(src, "utf8").replace(/\{\{([A-Z_]+)\}\}/g, (whole, key: string) =>
    key in map ? map[key]! : whole,
  );
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, body);
  chmodSync(dest, 0o600);
  log(`  env  ${dest}`);
}

function materializeEnv(inst: Instance): void {
  const root = join(WORKTREES, inst.slug.toUpperCase());
  if (inst.repos.includes(BE_REPO)) {
    renderEnv(inst, "backend.env.tmpl", join(root, BE_REPO, "backend", ".env.local"));
    renderEnv(inst, "agents.env.tmpl", join(root, BE_REPO, "agents", ".env.local"));
  }
  if (inst.repos.includes(FE_REPO)) {
    // FE-only / dev-backend instances point the frontend at the DEPLOYED dev
    // backend; full-stack instances point it at this instance's local BE.
    const feTemplate =
      inst.backend === "dev" ? "frontend-dev.env.tmpl" : "frontend.env.tmpl";
    renderEnv(inst, feTemplate, join(root, FE_REPO, "apps", "frontend", ".env.local"));
  }
}

// ── Git worktrees + deps ────────────────────────────────────────────────────
function ensureWorktree(inst: Instance, repo: string): string {
  const clone = join(REPOS, repo);
  const path = join(WORKTREES, inst.slug.toUpperCase(), repo);
  if (existsSync(path)) return path;
  if (!existsSync(join(clone, ".git"))) die(`clone missing: ${clone}`);
  log(`  worktree ${repo} @ ${inst.branch}`);
  sh("git", ["-C", clone, "fetch", "origin", BASE_BRANCH]);
  if (inst.branch === BASE_BRANCH) {
    // Tracking the base branch (e.g. the golden instance): the main clone
    // already has it checked out, so a second worktree on the same branch is
    // refused by git — use a detached checkout of origin/<base> instead.
    sh("git", ["-C", clone, "worktree", "add", "--detach", path, `origin/${BASE_BRANCH}`]);
    return path;
  }
  const branchExists =
    shOk("git", ["-C", clone, "show-ref", "--verify", `refs/heads/${inst.branch}`]) ||
    shOk("git", ["-C", clone, "show-ref", "--verify", `refs/remotes/origin/${inst.branch}`]);
  if (branchExists) {
    shOk("git", ["-C", clone, "fetch", "origin", inst.branch]);
    sh("git", ["-C", clone, "worktree", "add", path, inst.branch]);
  } else {
    sh("git", ["-C", clone, "worktree", "add", "-b", inst.branch, path, `origin/${BASE_BRANCH}`]);
  }
  return path;
}

function installDeps(inst: Instance): void {
  const root = join(WORKTREES, inst.slug.toUpperCase());
  const env = { PATH: `${HOME}/.local/bin:${HOME}/.bun/bin:${process.env["PATH"]}` };
  if (inst.repos.includes(FE_REPO)) {
    log("  install fluso-frontend (pnpm)");
    sh("pnpm", ["install", "--prefer-offline"], { cwd: join(root, FE_REPO), env });
  }
  if (inst.repos.includes(BE_REPO)) {
    log("  install premapp-backend (uv sync + bun install)");
    sh("uv", ["sync"], { cwd: join(root, BE_REPO, "backend"), env });
    sh("bun", ["install"], { cwd: join(root, BE_REPO, "agents"), env });
  }
}

// ── Shared deps + database ──────────────────────────────────────────────────
function ensureSharedDeps(): void {
  log("  shared deps (postgres/localstack/redis)");
  sh("docker", ["compose", "-f", DEPS_COMPOSE, "-p", "opentag-deps", "up", "-d"]);
  // First boot: postgres needs a few seconds before it accepts connections.
  for (let i = 0; i < 30; i++) {
    if (shOk("docker", ["exec", "opentag-deps-postgres", "pg_isready", "-U", "postgres"])) return;
    execFileSync("sleep", ["2"]);
  }
  die("shared postgres did not become ready");
}
function ensureDatabase(inst: Instance): void {
  const name = dbName(inst.slug);
  const exists = sh("docker", [
    "exec", "opentag-deps-postgres",
    "psql", "-U", "postgres", "-tAc",
    `SELECT 1 FROM pg_database WHERE datname='${name}'`,
  ]).trim();
  if (exists !== "1") {
    log(`  create database ${name}`);
    sh("docker", ["exec", "opentag-deps-postgres", "psql", "-U", "postgres", "-c", `CREATE DATABASE ${name}`]);
  }
}
function runMigrations(inst: Instance): void {
  log("  alembic upgrade head");
  const cwd = join(WORKTREES, inst.slug.toUpperCase(), BE_REPO, "backend");
  // .env.local (rendered) carries SERVER_DB_*/ALEMBIC_DB_* pointing at the
  // shared postgres + this instance's database.
  sh("bash", ["-lc", `set -a; source .env.local; set +a; uv run alembic upgrade head`], { cwd });
}

// ── Process management (tmux panes per service) ─────────────────────────────
function tmuxUp(name: string): boolean {
  return shOk("tmux", ["has-session", "-t", name]);
}
function startProc(name: string, cwd: string, cmd: string, logFile: string): void {
  if (tmuxUp(name)) return;
  mkdirSync(dirname(logFile), { recursive: true });
  // tmux executes command strings with /bin/sh (dash on this box), which
  // parses `source` and some env-file contents differently from bash — so
  // each service gets a real bash launcher script next to its log.
  const script = logFile.replace(/\.log$/, ".sh");
  writeFileSync(
    script,
    `#!/usr/bin/env bash
set -uo pipefail
export PATH=${HOME}/.local/bin:${HOME}/.bun/bin:$PATH
cd ${cwd}
exec >> ${logFile} 2>&1
${cmd}
`,
  );
  chmodSync(script, 0o755);
  sh("tmux", ["new-session", "-d", "-s", name, `bash ${script}`]);
  log(`  started ${name} (log ${logFile})`);
}
function stopProc(name: string): void {
  if (tmuxUp(name)) {
    sh("tmux", ["kill-session", "-t", name]);
    log(`  stopped ${name}`);
  }
}

// ── Commands ────────────────────────────────────────────────────────────────
function cmdCreate(slug: string, opts: Record<string, string | boolean>): void {
  if (!/^[a-z][a-z0-9-]{1,20}$/.test(slug)) die("slug must be lowercase alnum/hyphen, ≤21 chars");
  const reg = loadRegistry();
  const existing = reg.instances[slug];
  if (existing) {
    // Idempotent re-create: workflow retries / revision rounds land here.
    log(`re-ensure ${slug} (slot ${existing.slot})`);
    for (const r of existing.repos) ensureWorktree(existing, r);
    materializeEnv(existing);
    installDeps(existing);
    const dev = existing.backend === "dev";
    sh("sudo", [
      "/usr/local/bin/opentag-ingress", "add", slug,
      String(existing.ports.fe),
      dev ? "0" : String(existing.ports.be),
      dev ? "0" : String(existing.ports.agents),
    ]);
    existing.updatedAt = new Date().toISOString();
    saveRegistry(reg);
    return;
  }

  // --fe-only: a frontend-only change. Run just the FE against the DEPLOYED dev
  // backend (no local BE/agents/db). `--backend dev` is the same underlying
  // switch if you want to keep both worktrees but still target deployed dev.
  const feOnly = Boolean(opts["fe-only"]);
  const backend: "local" | "dev" =
    feOnly || opts["backend"] === "dev" ? "dev" : "local";
  const repos = feOnly
    ? [FE_REPO]
    : String(opts["repos"] ?? "fe,be")
        .split(",")
        .map((r) => (r.trim() === "fe" ? FE_REPO : r.trim() === "be" ? BE_REPO : r.trim()))
        .filter(Boolean);

  const used = new Set(Object.values(reg.instances).map((i) => i.slot));
  const slot = SLOTS.find((s) => !used.has(s)) ?? die("no free slots (3–9) — wt destroy something first");
  const ports = portsFor(slot);
  // FE-only only needs its FE port free; the BE/agents ports go unused.
  const portsToCheck = repos.includes(BE_REPO)
    ? Object.entries(ports)
    : ([["fe", ports.fe]] as [string, number][]);
  for (const [k, p] of portsToCheck) {
    if (!portFree(p)) die(`slot ${slot} port ${k}=${p} is unexpectedly busy — check ss -tlnp / PORTS.md`);
  }

  const inst: Instance = {
    slug,
    issue: typeof opts["issue"] === "string" ? (opts["issue"] as string).toUpperCase() : undefined,
    branch: (opts["branch"] as string) || `athena/${slug}`,
    slot,
    repos,
    ports,
    backend,
    state: "created",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  log(
    `create ${slug} (slot ${slot}, branch ${inst.branch}` +
      (backend === "dev" ? ", frontend-only → deployed dev backend" : "") +
      ")",
  );
  for (const r of inst.repos) ensureWorktree(inst, r);
  materializeEnv(inst);
  installDeps(inst);

  const h = hostnames(slug);
  log("  cloudflared ingress");
  // FE-only: only route the app hostname; -api/-agents have nothing to serve.
  const ingressArgs =
    backend === "dev"
      ? ["add", slug, String(ports.fe), "0", "0"]
      : ["add", slug, String(ports.fe), String(ports.be), String(ports.agents)];
  sh("sudo", ["/usr/local/bin/opentag-ingress", ...ingressArgs]);

  reg.instances[slug] = inst;
  saveRegistry(reg);
  const urls =
    backend === "dev"
      ? `https://${h.fe} (→ deployed dev backend)`
      : `https://${h.fe} · https://${h.be} · https://${h.agents}`;
  log(`created. next: wt start ${slug}   (urls: ${urls})`);
}

async function cmdStart(slug: string, opts: Record<string, string | boolean>): Promise<void> {
  const reg = loadRegistry();
  const inst = reg.instances[slug] ?? die(`unknown instance '${slug}'`);
  const root = join(WORKTREES, slug.toUpperCase());
  const logs = join(root, "logs");
  const h = hostnames(slug);

  if (inst.repos.includes(BE_REPO)) {
    ensureSharedDeps();
    ensureDatabase(inst);
    runMigrations(inst);
    startProc(
      tmuxName(slug, "be"),
      join(root, BE_REPO, "backend"),
      `set -a && source .env.local && set +a && uv run uvicorn aci.server.main:app --host 127.0.0.1 --port ${inst.ports.be}`,
      join(logs, "be.log"),
    );
    startProc(
      tmuxName(slug, "ag"),
      join(root, BE_REPO, "agents"),
      `set -a && source .env.local && set +a && bun gateway.ts`,
      join(logs, "ag.log"),
    );
    if (opts["with"] === "chronograph" || inst.withChronograph) {
      inst.withChronograph = true;
      startProc(
        tmuxName(slug, "cg"),
        join(root, BE_REPO, "chronograph"),
        `set -a && source ../backend/.env.local && set +a && uv run uvicorn main:app --host 127.0.0.1 --port ${inst.ports.chrono}`,
        join(logs, "cg.log"),
      );
    }
  }

  if (inst.repos.includes(FE_REPO)) {
    const feDir = join(root, FE_REPO, "apps", "frontend");
    if (!existsSync(join(feDir, ".next", "BUILD_ID"))) {
      log("  next build (serialized, capped memory — this takes a few minutes)");
      sh("bash", [
        "-lc",
        `exec 9>${BUILD_LOCK} && flock 9 && cd ${feDir} && NODE_OPTIONS=--max-old-space-size=4096 pnpm build`,
      ]);
    }
    startProc(
      tmuxName(slug, "fe"),
      feDir,
      // HOSTNAME (not -H): Next uses it to build absolute redirect URLs
      // (Clerk auth) — the -H flag only changes the bind interface.
      `HOSTNAME=${h.fe} PORT=${inst.ports.fe} NODE_OPTIONS=--max-old-space-size=2048 pnpm start`,
      join(logs, "fe.log"),
    );
  }

  if (inst.repos.includes(BE_REPO)) {
    await waitFor("backend", `http://127.0.0.1:${inst.ports.be}/v1/health`, 120);
    await waitFor("agents gateway", `http://127.0.0.1:${inst.ports.agents}/healthz`, 90);
  }
  if (inst.repos.includes(FE_REPO)) {
    await waitFor("frontend", `http://127.0.0.1:${inst.ports.fe}/`, 90);
  }

  inst.state = "running";
  inst.updatedAt = new Date().toISOString();
  saveRegistry(reg);
  log(
    inst.backend === "dev"
      ? `running:  https://${h.fe}  (frontend-only → deployed dev backend)`
      : `running:  https://${h.fe}\n  api:    https://${h.be}\n  agents: https://${h.agents}`,
  );
}

function cmdStop(slug: string): void {
  const reg = loadRegistry();
  const inst = reg.instances[slug] ?? die(`unknown instance '${slug}'`);
  for (const p of ["fe", "ag", "be", "cg"]) stopProc(tmuxName(slug, p));
  inst.state = "stopped";
  inst.updatedAt = new Date().toISOString();
  saveRegistry(reg);
}

function cmdDestroy(slug: string): void {
  const reg = loadRegistry();
  const inst = reg.instances[slug] ?? die(`unknown instance '${slug}'`);
  cmdStop(slug);
  sh("sudo", ["/usr/local/bin/opentag-ingress", "remove", slug]);
  for (const r of inst.repos) {
    const path = join(WORKTREES, slug.toUpperCase(), r);
    if (existsSync(path)) {
      log(`  git worktree remove ${r}`);
      shOk("git", ["-C", join(REPOS, r), "worktree", "remove", path, "--force"]) ||
        log(`  (worktree remove failed for ${r} — clean up manually)`);
    }
  }
  delete reg.instances[slug];
  saveRegistry(reg);
  log(`destroyed ${slug} (database ${dbName(slug)} kept — drop manually if wanted)`);
}

async function cmdStatus(slug?: string): Promise<void> {
  const reg = loadRegistry();
  const list = slug ? [reg.instances[slug] ?? die(`unknown instance '${slug}'`)] : Object.values(reg.instances);
  if (list.length === 0) {
    log("no instances. create one: wt create <slug> [--issue FLU-x] [--branch <br>]");
  }
  for (const inst of list) {
    const h = hostnames(inst.slug);
    const procs = ["be", "ag", "fe", "cg"]
      .map((p) => `${p}:${tmuxUp(tmuxName(inst.slug, p)) ? "up" : "-"}`)
      .join(" ");
    let health = "";
    if (inst.state === "running" && inst.repos.includes(BE_REPO)) {
      try {
        const r = await fetch(`http://127.0.0.1:${inst.ports.be}/v1/health`, { signal: AbortSignal.timeout(3000) });
        health = r.ok ? " health:ok" : ` health:HTTP${r.status}`;
      } catch {
        health = " health:DOWN";
      }
    }
    log(
      `${inst.slug}  slot=${inst.slot} issue=${inst.issue ?? "-"} branch=${inst.branch} state=${inst.state}` +
        `\n  ports fe:${inst.ports.fe} be:${inst.ports.be} ag:${inst.ports.agents}  procs ${procs}${health}` +
        `\n  https://${h.fe}`,
    );
  }
  const used = new Set(Object.values(reg.instances).map((i) => i.slot));
  log(`free slots: ${SLOTS.filter((s) => !used.has(s)).join(", ") || "none"}`);
}

function cmdUrl(slug: string): void {
  const reg = loadRegistry();
  if (!reg.instances[slug]) die(`unknown instance '${slug}'`);
  const h = hostnames(slug);
  log(`https://${h.fe}\nhttps://${h.be}\nhttps://${h.agents}`);
}

function cmdEnv(slug: string): void {
  const reg = loadRegistry();
  const inst = reg.instances[slug] ?? die(`unknown instance '${slug}'`);
  materializeEnv(inst);
  log("env re-rendered. restart the instance to pick it up: wt stop && wt start");
}

// ── Main ────────────────────────────────────────────────────────────────────
function parseArgs(argv: string[]): { cmd: string; slug?: string; opts: Record<string, string | boolean> } {
  const [cmd, ...rest] = argv;
  const opts: Record<string, string | boolean> = {};
  const pos: string[] = [];
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i]!;
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = rest[i + 1];
      if (next && !next.startsWith("--")) {
        opts[key] = next;
        i++;
      } else opts[key] = true;
    } else pos.push(a);
  }
  return { cmd: cmd ?? "help", slug: pos[0], opts };
}

const USAGE = `wt — OpenTag instance manager (see /home/omni/OpenTag/infra/DESIGN.md)

  wt create <slug> [--issue FLU-x] [--branch <br>] [--repos fe,be]
  wt create <slug> --fe-only          # frontend only, against the DEPLOYED dev backend
  wt start  <slug> [--with chronograph]
  wt stop   <slug>
  wt status [<slug>]
  wt url    <slug>
  wt env    <slug>
  wt destroy <slug>`;

const { cmd, slug, opts } = parseArgs(process.argv.slice(2));
switch (cmd) {
  case "create":  cmdCreate(slug ?? die("slug required"), opts); break;
  case "start":   await cmdStart(slug ?? die("slug required"), opts); break;
  case "stop":    cmdStop(slug ?? die("slug required")); break;
  case "destroy": cmdDestroy(slug ?? die("slug required")); break;
  case "status":  await cmdStatus(slug); break;
  case "url":     cmdUrl(slug ?? die("slug required")); break;
  case "env":     cmdEnv(slug ?? die("slug required")); break;
  default: log(USAGE);
}
